# Имя проекта
name: template
# Описание проекта
description: The Template for new flutter project
# Версия проекта
version: 1.0.0+1

publish_to: 'none' # Удалить, если надо чтобы этот проект был опубликован на pub.dev

# Версия SDK
environment:
  sdk: '>=3.1.3 <4.0.0'


# --------------------------------------
# Зависимости для проекта
# --------------------------------------
dependencies:
  # Flutter
  flutter:
    sdk: flutter
  # Http запросы
  http: ^0.13.3
  # Поддержка env
  flutter_dotenv: ^5.0.2
  # Иконки
  cupertino_icons: ^1.0.2
  # Локализация приложения
  flutter_localizations:
    sdk: flutter
  # Локальное хранилище
  shared_preferences: ^2.2.2
  # Глобальное хранилище
  redux: ^5.0.0
  flutter_redux: ^0.9.0
  # Разрешения приложения
  permission_handler: ^11.2.0
  # Открывать ссылки в браузере
  url_launcher: ^6.2.4
  # Выбор картинок из галереи или камеры
  image_picker: ^0.8.5+3
  # Кеширование картинок
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1


# --------------------------------------
# Dev зависимости для проекта
# --------------------------------------
dev_dependencies:
  # Генерация иконок
  flutter_launcher_icons: ^0.11.0
  # Переключение по ссылкам в коде
  flutter_lints: ^2.0.0


# --------------------------------------
# Настройки
# --------------------------------------
# Настройки генерации иконок
flutter_icons:
  android: "lc_launcher"
  ios: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 21

# Настройки Flutter
flutter:
  # Автоматическая генерирация кода (для локализации)
  generate: true

  # Набор виджетов
  uses-material-design: true

  # Пути к ресурсам, которые должны быть включены в проект
  assets:
    - assets/img/
    - assets/icons/
    - .env

  # Шрифты
  fonts:
    # Иконки FontAwesomePro
    - family: FontAwesomePro
      fonts:
        - asset: assets/fonts/FontAwesome-Regular.ttf

    # Стандартный шрифт
    - family: Circe
      fonts:
        - asset: assets/fonts/Circe-Light.ttf
          weight: 300
        - asset: assets/fonts/Circe-Regular.ttf
          weight: 400
        - asset: assets/fonts/Circe-Bold.ttf
          weight: 700
