# Имя проекта
name: template
# Описание проекта
description: The Template for new flutter project
# Версия проекта
version: 1.0.0+1

publish_to: 'none' # Удалить, если надо чтобы этот проект был опубликован на pub.dev

# Версия SDK
environment:
  sdk: '>=3.1.3 <4.0.0'

# --------------------------------------
# Зависимости для проекта
# --------------------------------------
dependencies:
  # Flutter
  flutter:
    sdk: flutter
  # Http запросы
  http: ^0.13.3
  # Поддержка env
  flutter_dotenv: ^5.0.2
  # Иконки
  cupertino_icons: ^1.0.2
  # Локализация приложения
  flutter_localizations:
    sdk: flutter
  # Локальное хранилище
  shared_preferences: any
  # Глобальное хранилище
  redux: ^5.0.0
  flutter_redux: ^0.9.0
  # Выбор картинок из галереи или камеры
  image_picker: ^0.8.5+3
  # Font Awesome Иконки
  font_awesome_flutter: ^10.6.0

# --------------------------------------
# Dev зависимости для проекта
# --------------------------------------
dev_dependencies:
  # Переключение по ссылкам в коде
  flutter_lints: ^2.0.0

# --------------------------------------
# Настройки flutter
# --------------------------------------
flutter:
  # Автоматическая генерирация кода (для локализации)
  generate: true

  # Набор виджетов
  uses-material-design: true

  # Пути к ресурсам, которые должны быть включены в проект
  assets:
    - assets/img/
    - assets/icons/
    - .env

  # Шрифты
  fonts:
    - family: FontAwesomePro
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf

    - family: Circe
      fonts:
        - asset: assets/fonts/Circe-Light.ttf
          weight: 300
        - asset: assets/fonts/Circe-Regular.ttf
          weight: 400
        - asset: assets/fonts/Circe-Bold.ttf
          weight: 700
