name: tproject
description: "Template for project"
version: 1.0.0
publish_to: 'none'
environment:
  sdk: ^3.5.2


# --------------- PACKAGES --------------- #

dependencies:
  flutter:
    sdk: flutter

  # API
  dio: ^5.7.0

  # Local storage
  get_storage: ^2.1.1

  # State management
  get: ^4.6.6

  # Svg
  flutter_svg: ^2.0.10+1

  # Formatting data
  intl: ^0.19.0

  # Permissions
  permission_handler: ^11.3.1

  # Logging code
  logger: ^2.4.0

  # Web links
  url_launcher: ^6.3.0

  # Dynamic height elements in grid
  flutter_staggered_grid_view: ^0.7.0

  # Images caching
  cached_network_image: ^3.4.0

  # Firebase and notifications
  firebase_core: ^3.4.0
  firebase_messaging: 15.1.1


# --------------- DEV PACKAGES --------------- #

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  # --------------- ASSETS --------------- #

  assets:
    - assets/
    - assets/img/
    - assets/icons/

  # --------------- FONTS --------------- #

  fonts:
    # Base font
    - family: Circe
      fonts:
        - asset: assets/fonts/Circe-Light.ttf
          weight: 300
        - asset: assets/fonts/Circe-Regular.ttf
          weight: 400
        - asset: assets/fonts/Circe-Bold.ttf
          weight: 700

    # Icons fontAwesome
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome-Light.ttf
          weight: 300
        - asset: assets/fonts/FontAwesome-Regular.ttf
          weight: 400
        - asset: assets/fonts/FontAwesome-Bold.ttf
          weight: 700